global:
  scrape_interval: 5s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets: 
        - alert_manager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: go_app
    static_configs:
      - targets: ["go_app:8080"]
  - job_name: node_exporter
    static_configs:
      - targets: ["node:9100"]
  - job_name: demo
    static_configs:
      - targets: 
        - demo.promlabs.com:10000
        - demo.promlabs.com:10001
        - demo.promlabs.com:10002
